version: "3"
services:
  mongodb:
    container_name: yap-mongodb
    image: mongo:8.0-noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - yap_mongo_data:/data/db

  backend:
    container_name: yap-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3535:3535"
      - "3000:3000"
    depends_on:
      - mongodb
    env_file: "./backend/.env"

  frontend:
    container_name: yap-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file: "./frontend/.env"

volumes:
  yap_mongo_data:
    driver: local
