version: "3"
services:
  mongodb:
    container_name: yap-mongodb
    image: mongo:8.0-noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - yap_mongo_data:/data/db

  backend:
    container_name: yap-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3535:3535"
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3535
      - WEBRTC_PORT=3000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/?authSource=admin
      - FRONTEND_URL=http://localhost:5173
      - JWT_SECRET=YOUR_JWT_SECRET
      - CLOUDINARY_CLOUD_NAME=your_cloud_name
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_secret
      - ENCRYPTION_KEY=your_encryption_key

  frontend:
    container_name: yap-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_SIGNALING_URL=http://localhost:3000
      - VITE_API_URL=http://localhost:3535
      - CHOKIDAR_USEPOLLING=true
      - VITE_PORT=5173

volumes:
  yap_mongo_data:
    driver: local
