version: "3"
services:
  mongodb:
    container_name: yap-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - yap_mongo_data:/data/db

  backend:
    container_name: yap-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4545:3535"
      - "4000:3000"
    depends_on:
      - mongodb
    env-file: ./backend/.env

volumes:
  yap_mongo_data:
    driver: local
